### ISSUE TITLE
Mutating State

### ISSUE THREAD

**Issue by sjlagasse** [Berava/jammming#1]
In App.js you mutate state directly. You use `push` in `addTrack` and `splice` in `removeTrack`. Neither of these arrays methods return a new array and instead act on them directly. Instead, you things like `concat` and `slice`. 

Here is an example:

```
const newState = this.state.playlistTracks.concat(track);
this.setState({
  playlistTracks: newState
});
```

**Comment by Berava** [comment]
Thx for this issue. It's now fixed.
